[package]
name = "veil_signal"
version = "0.0.1"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }

[addresses]
initia_std = "0x1"
std = "0x1"
# Your address: init1fws7ncn4aasm2mye2vksqejsvsmzq8tnpn84l6
veil = "0x4Ba1e9e275EF61B56C99532D0066506436201D73"

[dev-addresses]
veil = "0xcafe"
